### PR TITLE
capture version from the installed package

### PR DESCRIPTION
**Pull request by kasperk81**
redoing https://github.com/compiler-explorer/dotnet-builder/pull/7 with exception for < v8 and support for multi-digit major versions.

### CODE REVIEW

**Review by mattgodbolt — APPROVED** [review]

**Comment by mattgodbolt** [comment]
Does this require a rebuild of all the compilers?

**Comment by kasperk81** [comment]
only the nightly build of trunk branch. i'll keep an eye out. --aot was working when we first implemented it, i'll try to revive it by figuring out how the other recent changes might have impacted it.

**Comment by hez2010** [comment]
This is breaking the trunk build. We don't publish nightly aot packages on nuget.org so the restore would fail.
I think we would better to disable AOT build for trunk at all.

**Comment by kasperk81** [comment]
no, your changes broke the aot trunk. when i first added it, it was building fine. we are not using nuget but a local store. see the other pr fixing it again..

**Comment by hez2010** [comment]
See https://github.com/compiler-explorer/compiler-workflows/actions/runs/6502373123
Your changes make the trunk build failed at `dotnet publish`. The main branch has been bumped to net9.0 but we don't have 9.0 ilc package on nuget.org, so it will fail when build the image. 

```
  + /root/dotnet/runtime/dotnet.sh publish -p:PublishAot=true --packages /root/dotnet/runtime/artifacts/tests/coreclr/linux.x64.Release/Tests/Core_Root/aot app
  MSBuild version 17.7.0+5785ed5c2 for .NET
    Determining projects to restore...
  /tmp/app/app.csproj : warning NU1603: app depends on Microsoft.NET.ILLink.Tasks (>= 8.0.0-rc.1.23414.4) but Microsoft.NET.ILLink.Tasks 8.0.0-rc.1.23414.4 was not found. An approximate best match of Microsoft.NET.ILLink.Tasks 8.0.0-rc.1.23419.4 was resolved.
  /tmp/app/app.csproj : error NU1102: Unable to find package Microsoft.DotNet.ILCompiler with version (>= 9.0.0) 
```

> your changes broke the aot trunk

I disabled the build for aot trunk as a workaround deliberately because it doesn't work and prevent trunk image being built.

**Comment by kasperk81** [comment]
now you are showing me the logs? build was failing for whole month after your change when i fixed it https://github.com/compiler-explorer/dotnet-builder/pull/7#issue-1924480911 and you immediately opened another pr overwriting changes.

this has nothing to do with nuget.org. we are using LOCAL feed which you clearly don't know about. and if you don't know something, just ask.

the error is about wrong argument which other pr is fixing.

**Comment by hez2010** [comment]
> build was failing for whole month after your change

Yeah it was caused by this commit (3cae918759f1ee2913949bcd92f526f6689b4755) in #5 where I tried to enable aot build for trunk

Before that, we never built aot toolchains for trunk (we were only building it for net7.0). To see this, you can simply check the last successful build before 9/6: https://github.com/compiler-explorer/compiler-workflows/actions/runs/6103792630/job/16564818318, and you can observe that in trunk build we didn't build aot at all.

> you immediately opened another pr overwriting changes

This (#8) is to revert the 3cae918759f1ee2913949bcd92f526f6689b4755. The build failure was caused by enabling aot build for trunk, so the simplest solution is to disable it again. 

If you have solution to make aot build for trunk work then it's fine.
But worth to note that even it gets built, the `--aot` still won't work due to some permission issues (error 126 is 'Permission denied') and need some further fixes, see the example from net7.0 despites it has the aot toolchain being built successfully: https://godbolt.org/z/9vfM1fz54.

**Pull request merged**
