### PR TITLE
Unify constructor handling

### PR DESCRIPTION
**Pull request by hez2010**
Unify how we handle constructors, which enables us to disassemble constructors in a more reliable way.
I would like to request a rebuild of the image.

/cc: @mattgodbolt

### CODE REVIEW

**Review by mattgodbolt — APPROVED** [review]
Thanks

**Comment by mattgodbolt** [comment]
The image will build automatically - do you need the compilers to be rebuilt? If so which ones?

**Comment by hez2010** [comment]
> The image will build automatically - do you need the compilers to be rebuilt? If so which ones?

Would like to rebuild all existing compilers (v6.0.11, v6.0.14, v6.0.18, v7.0.1, v7.0.3, v7.0.7 and trunk) as this PR made changes to the disassembler. 

Ideally, we may consider move the disassembler (DisassemblyLoader) out of this repo so that we can update the disassembler without rebuilding existing images.

**Comment by mattgodbolt** [comment]
I'll look at doing this. A different repo or different way of getting the disassembler would be great, as this is a manual process on our end.

**Comment by mattgodbolt** [comment]
Sorry I haven't gotten around to this yet

**Comment by mattgodbolt** [comment]
Doing this right now having merged all the other PRs

**Comment by mattgodbolt** [comment]
The builds for v7.* failed.

```
  + /root/dotnet/runtime/dotnet.sh add app package runtime.linux-x64.microsoft.dotnet.ilcompiler --version 7.0.1 --package-directory /root/dotnet/runtime/artifacts/tests/coreclr/Linux.x64.Release/Tests/Core_Root/aot -s /root/dotnet/runtime/artifacts/tests/coreclr/Linux.x64.Release/Tests/Core_Root/aot
    Determining projects to restore...
    Writing /tmp/tmpyAqOoQ.tmp
  info : X.509 certificate chain validation will use the fallback certificate bundle at '/root/dotnet/runtime/.dotnet/sdk/7.0.100/trustedroots/codesignctl.pem'.
  info : X.509 certificate chain validation will use the fallback certificate bundle at '/root/dotnet/runtime/.dotnet/sdk/7.0.100/trustedroots/timestampctl.pem'.
  info : Adding PackageReference for package 'runtime.linux-x64.microsoft.dotnet.ilcompiler' into project '/tmp/app/app.csproj'.
  info : Restoring packages for /tmp/app/app.csproj...
  info : Installed runtime.linux-x64.Microsoft.DotNet.ILCompiler 7.0.1 from /root/dotnet/runtime/artifacts/tests/coreclr/Linux.x64.Release/Tests/Core_Root/aot with content hash zDimPcxvzwFldjFuclIn2QZA8b6ibwUG0tyOSHEOr/OEoR2jhHgJ1CdZa0y4BuPet3Kbuy4Ilg9FWCHaEiHxQQ==.
  info : Package 'runtime.linux-x64.microsoft.dotnet.ilcompiler' is compatible with all the specified frameworks in project '/tmp/app/app.csproj'.
  info : PackageReference for package 'runtime.linux-x64.microsoft.dotnet.ilcompiler' version '7.0.1' added to file '/tmp/app/app.csproj'.
  info : Generating MSBuild file /tmp/app/obj/app.csproj.nuget.g.props.
  info : Writing assets file to disk. Path: /tmp/app/obj/project.assets.json
  log  : Restored /tmp/app/app.csproj (in 888 ms).
  + /root/dotnet/runtime/dotnet.sh publish -p:PublishAot=true --packages /root/dotnet/runtime/artifacts/tests/coreclr/Linux.x64.Release/Tests/Core_Root/aot app
  MSBuild version 17.4.0+18d5aef85 for .NET
    Determining projects to restore...
    Restored /tmp/app/app.csproj (in 3.93 sec).
    app -> /tmp/app/bin/Debug/net7.0/linux-x64/app.dll
  /root/dotnet/runtime/artifacts/tests/coreclr/Linux.x64.Release/Tests/Core_Root/aot/microsoft.dotnet.ilcompiler/7.0.1/build/Microsoft.DotNet.ILCompiler.SingleEntry.targets(49,5): warning : Set PublishAot property to true and delete explicit 'Microsoft.DotNet.ILCompiler' package reference in your project file. Explicit 'Microsoft.DotNet.ILCompiler' package reference can run into version errors. [/tmp/app/app.csproj]
    Generating native code
    app -> /tmp/app/bin/Debug/net7.0/linux-x64/publish/
  ++ find /root/dotnet/runtime/artifacts/tests/coreclr/Linux.x64.Release/Tests/Core_Root/aot -type f -name ilc
  ++ head -1
  + ILC=/root/dotnet/runtime/artifacts/tests/coreclr/Linux.x64.Release/Tests/Core_Root/aot/runtime.linux-x64.microsoft.dotnet.ilcompiler/7.0.1/tools/ilc
  ++ /root/dotnet/runtime/artifacts/tests/coreclr/Linux.x64.Release/Tests/Core_Root/aot/runtime.linux-x64.microsoft.dotnet.ilcompiler/7.0.1/tools/ilc --version
  error: invalid option --version
  + PACKAGE_VERSION=
```

**Comment by mattgodbolt** [comment]
That may be from 56edb577f36588171dc1292af4a0c1a92e7da380 via @kasperk81  #7

**Comment by mattgodbolt** [comment]
These are all deployed now (or should be...let me know if you have issues)

**Comment by hez2010** [comment]
It's working as expected. Thanks!

**Pull request merged**
